version: 2

models:

  - name: stg_employees
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique

  - name: stg_departments
    columns:
      - name: department_id
        tests:
          - not_null
          - unique
  - name: stg_product
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: student_id
        tests:
          - not_null
      - name: product_id
        tests:
            - not_null
      - name: quantity
        tests:
            - not_null
      - name: total_amount
        tests:
            - not_null



